### PR TITLE
Addressed reset fix

### LINKED ISSUE #31: mlx90632_set_meas_type fail after addressed reset command
Hi,

Setup:
nrf52840, i2c clock is running at 400 kHz.

I'm having an issue with `mlx90632_set_meas_type` which is failing every time. After `mlx90632_addressed_reset` has been called, the next `mlx90632_i2c_read` will fail. I can see a NACK is received after the i2c address has been sent.

In this case, a repeated `mlx90632_i2c_read` fix the problem.

Thanks

### PR DESCRIPTION
**Pull request by slavysis**
Fixes #31

### CODE REVIEW

File: src/mlx90632.c [hunk 1]
```diff
@@ -475,14 +475,28 @@ int32_t mlx90632_init(void)
...
+    uint16_t reg_ctrl;
+    uint16_t reg_value;
+
+    ret = mlx90632_i2c_read(MLX90632_REG_CTRL, &reg_value);
+    if (ret < 0)
+        return ret;
+
+    reg_ctrl = reg_value & ~MLX90632_CFG_PWR_MASK;
+    reg_ctrl |= MLX90632_PWR_STATUS_STEP;
+    ret = mlx90632_i2c_write(MLX90632_REG_CTRL, reg_ctrl);
```
Comment (Letme) [inline src/mlx90632.c:487]: wouldn't it be better if we would just hardcode it to the power mode? That way we create constant environment for the command in case any other combination also has a problem...

```suggestion
    ret = mlx90632_i2c_write(MLX90632_REG_CTRL, MLX90632_PWR_STATUS_STEP);
```

Comment (slavysis) [reply src/mlx90632.c:487]: Since the issue is only in sleeping step mode, I would rather keep all the other settings in the control register and only change the mode to step. I do not really like fixing the value as it might lead to needlessly changing the settings back and forth.
